// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkfD4HqkHCI8o-omIVfMxCyBBX8HRl6h0',
    appId: '1:99045961967:web:43ed0eb003a38a65e22b1a',
    messagingSenderId: '99045961967',
    projectId: 'itdev-cb722',
    authDomain: 'itdev-cb722.firebaseapp.com',
    storageBucket: 'itdev-cb722.firebasestorage.app',
    measurementId: 'G-J1HWKNLMHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXZ2l0jkeNQPpaQ5lIHkgfeqSrYTaKJ_Y',
    appId: '1:99045961967:android:19c4f3e1006ac222e22b1a',
    messagingSenderId: '99045961967',
    projectId: 'itdev-cb722',
    storageBucket: 'itdev-cb722.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADdTFfqokskEL-QZ4TkV4_jIPw7HBgTXo',
    appId: '1:99045961967:ios:8072f71fc410690ce22b1a',
    messagingSenderId: '99045961967',
    projectId: 'itdev-cb722',
    storageBucket: 'itdev-cb722.firebasestorage.app',
    iosBundleId: 'com.example.jTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADdTFfqokskEL-QZ4TkV4_jIPw7HBgTXo',
    appId: '1:99045961967:ios:8072f71fc410690ce22b1a',
    messagingSenderId: '99045961967',
    projectId: 'itdev-cb722',
    storageBucket: 'itdev-cb722.firebasestorage.app',
    iosBundleId: 'com.example.jTour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkfD4HqkHCI8o-omIVfMxCyBBX8HRl6h0',
    appId: '1:99045961967:web:a54a6e5e0078a097e22b1a',
    messagingSenderId: '99045961967',
    projectId: 'itdev-cb722',
    authDomain: 'itdev-cb722.firebaseapp.com',
    storageBucket: 'itdev-cb722.firebasestorage.app',
    measurementId: 'G-PP0RWC84JR',
  );
}
